[project]
name = "bach-or-bot"
version = "0.1.0"
description = "A binary classifier to distinguish between Human-composed and AI-generated music"
authors = [
    {name = "Acelle Krislette Rosales",email = "acellekrislette@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11,<3.14"
dependencies = [
    "librosa (>=0.11.0,<0.12.0)",
    "pandas (>=2.3.2,<3.0.0)",
    "soundfile (>=0.13.1,<0.14.0)",
    "torchaudio (>=2.8.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
